import { PrismaClient, ListingType, CategoryEnum, ListingStatus } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seed for City Discovery (Abeokuta Edition)...');

  // 1. Clean up existing listings and relations
  console.log('🧹 Clearing old corrupted or stale listing data...');
  await prisma.listingImage.deleteMany();
  await prisma.eventDetails.deleteMany();
  await prisma.restaurantDetails.deleteMany();
  await prisma.facilityDetails.deleteMany();
  await prisma.listing.deleteMany();

  // 2. Seed Super Admin User
  const adminEmail = 'okeolamide.o@yopmail.com';
  const adminPassword = 'Diamond13';
  const passwordHash = await bcrypt.hash(adminPassword, 10);

  const admin = await prisma.adminUser.upsert({
    where: { email: adminEmail },
    update: {
      role: 'super_admin',
      passwordHash,
      isActive: true,
    },
    create: {
      name: 'Super Admin',
      email: adminEmail,
      passwordHash,
      role: 'super_admin',
      isActive: true,
    },
  });
  console.log(`  ✓ Super Admin ready: ${admin.email} [${admin.role}]`);

  // Sample verified CAC & license document URLs
  const sampleLegalDocs = [
    'https://res.cloudinary.com/city-discovery/image/upload/v1710000001/legal/cac_certificate_verified.pdf',
    'https://res.cloudinary.com/city-discovery/image/upload/v1710000002/legal/operating_license_ogun_state.pdf',
    'https://res.cloudinary.com/city-discovery/image/upload/v1710000003/legal/health_safety_compliance_cert.pdf',
  ];

  // 3. Seed Events (Abeokuta)
  const events = [
    {
      title: 'Olumo Rock Heritage & Arts Fiesta 2026',
      description: 'An immersive 3-day cultural showcase celebrating Egba heritage, traditional music, Adire textile art exhibits, and night-time guided climbs to the summit of the sacred Olumo Rock.',
      category: CategoryEnum.arts_culture,
      neighborhood: 'Ikija',
      address: 'Olumo Rock Complex, Ikija, Abeokuta, Ogun State',
      latitude: 7.1594,
      longitude: 3.3444,
      thumbnailUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=1080&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?q=80&w=1080&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1080&auto=format&fit=crop',
      ],
      legalDocs: [sampleLegalDocs[0], sampleLegalDocs[1]],
      contactPhone: '+2348031234567',
      contactEmail: 'olumofestival@yopmail.com',
      externalLink: 'https://tickets.olumofestival.ng',
      submitterName: 'Ogun Arts Council',
      submitterEmail: 'ogunartscouncil@yopmail.com',
      submitterPhone: '+2348031234567',
      isFeatured: true,
      featuredOrder: 1,
      startDateTime: new Date(Date.now() + 1000 * 60 * 60 * 24 * 3), // 3 days from now
      endDateTime: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5),
    },
    {
      title: 'Abeokuta Tech & Innovation Summit 2026',
      description: 'The biggest gathering of developers, startup founders, angel investors, and tech enthusiasts across South-West Nigeria with hackathons, panel sessions, and VC pitch arenas.',
      category: CategoryEnum.education,
      neighborhood: 'Ibara',
      address: 'Ogun Tech Hub, Kobape Road / Ibara, Abeokuta, Ogun State',
      latitude: 7.1458,
      longitude: 3.3326,
      thumbnailUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=1080&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?q=80&w=1080&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=1080&auto=format&fit=crop',
      ],
      legalDocs: [sampleLegalDocs[0]],
      contactPhone: '+2348123456789',
      contactEmail: 'abeokutatech@yopmail.com',
      externalLink: 'https://abeokutatech.ng/register',
      submitterName: 'Ogun Innovators Network',
      submitterEmail: 'oguninnovators@yopmail.com',
      submitterPhone: '+2348123456789',
      isFeatured: true,
      featuredOrder: 2,
      startDateTime: new Date(Date.now() + 1000 * 60 * 60 * 24 * 6), // 6 days from now
      endDateTime: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7),
    },
    {
      title: 'Lisabi Day Grand Cultural Carnival',
      description: 'Annual historic festival commemorating the legendary hero Lisabi Agbongbo Akala with royal parades, traditional drumming contests, equestrian displays, and wrestling tourneys.',
      category: CategoryEnum.arts_culture,
      neighborhood: 'Ake',
      address: 'Alake Palace Grounds, Ake, Abeokuta, Ogun State',
      latitude: 7.1512,
      longitude: 3.3541,
      thumbnailUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=1080&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=1080&auto=format&fit=crop',
      ],
      legalDocs: [sampleLegalDocs[0], sampleLegalDocs[1]],
      contactPhone: '+2348023456781',
      contactEmail: 'lisabiday@yopmail.com',
      externalLink: 'https://lisabiday.org',
      submitterName: 'Egba Traditional Council',
      submitterEmail: 'egbacouncil@yopmail.com',
      submitterPhone: '+2348023456781',
      isFeatured: true,
      featuredOrder: 3,
      startDateTime: new Date(Date.now() + 1000 * 60 * 60 * 24 * 10), // 10 days from now
      endDateTime: new Date(Date.now() + 1000 * 60 * 60 * 24 * 12),
    },
    {
      title: 'June 12 Mega Comedy & Live Music Night',
      description: 'An evening of non-stop laughter and high-energy Afrobeat grooves featuring top national stand-up comedians and South-West musical icons in a state-of-the-art auditorium.',
      category: CategoryEnum.comedy,
      neighborhood: 'Kuto',
      address: 'June 12 Cultural Centre Main Bowl, Kuto, Abeokuta, Ogun State',
      latitude: 7.1425,
      longitude: 3.3488,
      thumbnailUrl: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?q=80&w=1080&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=1080&auto=format&fit=crop',
      ],
      legalDocs: [sampleLegalDocs[0]],
      contactPhone: '+2348051239876',
      contactEmail: 'laughrockcity@yopmail.com',
      externalLink: 'https://laughrockcity.ng',
      submitterName: 'RockCity Entertainment',
      submitterEmail: 'rockcityent@yopmail.com',
      submitterPhone: '+2348051239876',
      isFeatured: true,
      featuredOrder: 4,
      startDateTime: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14), // 14 days from now
      endDateTime: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14 + 1000 * 60 * 60 * 6),
    },
    {
      title: 'Gateway City 10K Marathon & Fitness Walk',
      description: 'Annual city run traversing through scenic Abeokuta landmarks from MKO Abiola Stadium through Ibara, Omida, and ending with an energetic aerobics concert.',
      category: CategoryEnum.sports,
      neighborhood: 'Kuto',
      address: 'MKO Abiola Stadium, Kuto, Abeokuta, Ogun State',
      latitude: 7.1395,
      longitude: 3.3512,
      thumbnailUrl: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?q=80&w=1080&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1530549387789-4c1017266635?q=80&w=1080&auto=format&fit=crop',
      ],
      legalDocs: [sampleLegalDocs[1]],
      contactPhone: '+2348076543210',
      contactEmail: 'gatewaymarathon@yopmail.com',
      externalLink: 'https://gatewaymarathon.ng',
      submitterName: 'Ogun Sports Commission',
      submitterEmail: 'ogunsports@yopmail.com',
      submitterPhone: '+2348076543210',
      isFeatured: false,
      featuredOrder: 0,
      startDateTime: new Date(Date.now() + 1000 * 60 * 60 * 24 * 18),
      endDateTime: new Date(Date.now() + 1000 * 60 * 60 * 24 * 18 + 1000 * 60 * 60 * 5),
    },
    {
      title: 'FUNAAB Campus Hack & AI Buildathon',
      description: 'A 48-hour student innovation sprint focused on building Agritech and Climate AI solutions for South-West Nigeria with cash prizes and startup incubation support.',
      category: CategoryEnum.education,
      neighborhood: 'Camp/FUNAAB',
      address: 'Federal University of Agriculture Abeokuta (FUNAAB) ICT Centre, Alabata Road, Abeokuta',
      latitude: 7.2285,
      longitude: 3.4418,
      thumbnailUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1080&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=1080&auto=format&fit=crop',
      ],
      legalDocs: [sampleLegalDocs[0]],
      contactPhone: '+2348099887766',
      contactEmail: 'funaabhack@yopmail.com',
      externalLink: 'https://funaabhack.dev',
      submitterName: 'FUNAAB Tech Society',
      submitterEmail: 'funaabtechsociety@yopmail.com',
      submitterPhone: '+2348099887766',
      isFeatured: false,
      featuredOrder: 0,
      startDateTime: new Date(Date.now() + 1000 * 60 * 60 * 24 * 22),
      endDateTime: new Date(Date.now() + 1000 * 60 * 60 * 24 * 24),
    },
    {
      title: 'Rock City Praise & Gospel Experience',
      description: 'An open-air worship gathering featuring top gospel choirs, mass choir orchestras, and spoken-word ministrations under the Abeokuta evening skyline.',
      category: CategoryEnum.religious,
      neighborhood: 'Oke-Mosan',
      address: 'Arcade Ground, Governor’s Office Complex, Oke-Mosan, Abeokuta',
      latitude: 7.1320,
      longitude: 3.3650,
      thumbnailUrl: 'https://images.unsplash.com/photo-1438232992991-995b7058bbb3?q=80&w=1080&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?q=80&w=1080&auto=format&fit=crop',
      ],
      legalDocs: [sampleLegalDocs[0]],
      contactPhone: '+2348033221100',
      contactEmail: 'rockcitygospel@yopmail.com',
      externalLink: 'https://rockcitygospel.org',
      submitterName: 'Gateway Christian Fellowship',
      submitterEmail: 'gatewaychristian@yopmail.com',
      submitterPhone: '+2348033221100',
      isFeatured: false,
      featuredOrder: 0,
      startDateTime: new Date(Date.now() + 1000 * 60 * 60 * 24 * 28),
      endDateTime: new Date(Date.now() + 1000 * 60 * 60 * 24 * 28 + 1000 * 60 * 60 * 8),
    },
  ];

  for (const ev of events) {
    await prisma.listing.create({
      data: {
        listingType: 'event',
        title: ev.title,
        description: ev.description,
        category: ev.category,
        city: 'Abeokuta',
        neighborhood: ev.neighborhood,
        address: ev.address,
        latitude: ev.latitude,
        longitude: ev.longitude,
        thumbnailUrl: ev.thumbnailUrl,
        legalDocumentUrls: ev.legalDocs,
        contactPhone: ev.contactPhone,
        contactEmail: ev.contactEmail,
        externalLink: ev.externalLink,
        submitterName: ev.submitterName,
        submitterEmail: ev.submitterEmail,
        submitterPhone: ev.submitterPhone,
        status: 'approved',
        isPublished: true,
        isFeatured: ev.isFeatured,
        featuredOrder: ev.featuredOrder,
        images: {
          create: ev.gallery.map((url, idx) => ({
            imageUrl: url,
            sortOrder: idx,
          })),
        },
        eventDetails: {
          create: {
            startDateTime: ev.startDateTime,
            endDateTime: ev.endDateTime,
            isRecurring: false,
          },
        },
      },
    });
  }
  console.log(`  ✓ Seeded ${events.length} verified Abeokuta events`);

  // 4. Seed Restaurants (Abeokuta)
  const restaurants = [
    {
      title: 'The Bamboo Grove Restaurant & Lounge',
      description: 'Upscale dining nestled within the Olusegun Obasanjo Presidential Library (OOPL), offering authentic Nigerian cuisines, sizzling grills, fresh juices, and serene lakeside views.',
      category: CategoryEnum.food_drink,
      neighborhood: 'Oke-Mosan',
      address: 'OOPL Complex, Presidential Boulevard, Oke-Mosan, Abeokuta',
      latitude: 7.1362,
      longitude: 3.3615,
      thumbnailUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1080&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=1080&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?q=80&w=1080&auto=format&fit=crop',
      ],
      legalDocs: [sampleLegalDocs[0], sampleLegalDocs[1], sampleLegalDocs[2]],
      contactPhone: '+2348039900112',
      contactEmail: 'bamboogrove@yopmail.com',
      externalLink: 'https://oopl.org.ng/bamboo-grove',
      submitterName: 'Green Legacy Hospitality Ltd',
      submitterEmail: 'greenlegacyresort@yopmail.com',
      submitterPhone: '+2348039900112',
      cuisineType: 'Nigerian & Continental Fusion',
      priceRange: '$$$',
      operatingHours: 'Mon - Sun: 08:00 AM - 11:00 PM',
      menuLink: 'https://oopl.org.ng/menu.pdf',
      cacNumber: 'RC-1049281',
      licenseNumber: 'OG-HOSP-2024-88',
      isFeatured: true,
      featuredOrder: 5,
    },
    {
      title: 'Palm Restaurant at Park Inn by Radisson',
      description: 'World-class hospitality and dining experience in Abeokuta featuring buffet breakfasts, gourmet steak cuts, seafood specialties, and an executive poolside bar.',
      category: CategoryEnum.food_drink,
      neighborhood: 'Kuto',
      address: '1 Ibrahim Babangida Boulevard, Kuto, Abeokuta',
      latitude: 7.1408,
      longitude: 3.3495,
      thumbnailUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=1080&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=1080&auto=format&fit=crop',
      ],
      legalDocs: [sampleLegalDocs[0], sampleLegalDocs[1]],
      contactPhone: '+2347007234776',
      contactEmail: 'parkinn.abeokuta@yopmail.com',
      externalLink: 'https://radissonhotels.com/en-us/hotels/park-inn-abeokuta',
      submitterName: 'Park Inn Operations Team',
      submitterEmail: 'parkinnadmin@yopmail.com',
      submitterPhone: '+2347007234776',
      cuisineType: 'International & African Buffet',
      priceRange: '$$$$',
      operatingHours: '24 Hours Daily',
      menuLink: 'https://radissonhotels.com/abeokuta/dining-menu',
      cacNumber: 'RC-894721',
      licenseNumber: 'OG-HOTEL-2023-01',
      isFeatured: true,
      featuredOrder: 6,
    },
    {
      title: 'Surulere Amala & Native Kitchen Panseke',
      description: 'The legendary taste of hot Egba Amala, Abula (Gbegiri & Ewedu), goat meat, assorted bushmeat, and fresh fish. A culinary landmark loved by locals and visitors alike.',
      category: CategoryEnum.food_drink,
      neighborhood: 'Panseke',
      address: '14 Panseke Expressway, Opposite Omida Market Road, Abeokuta',
      latitude: 7.1479,
      longitude: 3.3361,
      thumbnailUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1080&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=1080&auto=format&fit=crop',
      ],
      legalDocs: [sampleLegalDocs[0], sampleLegalDocs[2]],
      contactPhone: '+2348028889999',
      contactEmail: 'surulereamala@yopmail.com',
      externalLink: 'https://surulereamala.com',
      submitterName: 'Alhaja Kudirat Olusanya',
      submitterEmail: 'kudirat.olusanya@yopmail.com',
      submitterPhone: '+2348028889999',
      cuisineType: 'Authentic Yoruba Native Delicacies',
      priceRange: '$',
      operatingHours: 'Mon - Sat: 07:30 AM - 08:30 PM',
      menuLink: 'https://surulereamala.com/menu',
      cacNumber: 'BN-2894102',
      licenseNumber: 'OG-FOOD-2022-41',
      isFeatured: false,
      featuredOrder: 0,
    },
    {
      title: 'Sky Bar & Rooftop Lounge Ibara',
      description: 'Vibrant nightlife hub with panoramic vistas of Abeokuta hills, craft cocktails, live DJ sets, finger foods, and weekend karaoke vibes.',
      category: CategoryEnum.nightlife,
      neighborhood: 'Ibara',
      address: 'Skyline Plaza, Lalubu Street, Ibara, Abeokuta',
      latitude: 7.1492,
      longitude: 3.3304,
      thumbnailUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?q=80&w=1080&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?q=80&w=1080&auto=format&fit=crop',
      ],
      legalDocs: [sampleLegalDocs[0], sampleLegalDocs[1]],
      contactPhone: '+2348160001122',
      contactEmail: 'skybaribara@yopmail.com',
      externalLink: 'https://skybaribara.ng',
      submitterName: 'Sky Lounge Ventures',
      submitterEmail: 'skylounge@yopmail.com',
      submitterPhone: '+2348160001122',
      cuisineType: 'Cocktails, Grills & Small Chops',
      priceRange: '$$',
      operatingHours: 'Tue - Sun: 04:00 PM - 03:00 AM',
      menuLink: 'https://skybaribara.ng/menu',
      cacNumber: 'RC-3184910',
      licenseNumber: 'OG-LIQUOR-2023-19',
      isFeatured: false,
      featuredOrder: 0,
    },
    {
      title: 'Sweet Sensation Food Court Kuto',
      description: 'Family-friendly fast food restaurant and pastry bakery serving pastries, jollof rice combos, shawarma, ice creams, and family combo platters.',
      category: CategoryEnum.food_drink,
      neighborhood: 'Kuto',
      address: 'Kuto Junction, Beside Guarantee Trust Bank, Kuto, Abeokuta',
      latitude: 7.1415,
      longitude: 3.3472,
      thumbnailUrl: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?q=80&w=1080&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1550547660-d9450f859349?q=80&w=1080&auto=format&fit=crop',
      ],
      legalDocs: [sampleLegalDocs[0], sampleLegalDocs[2]],
      contactPhone: '+2348091112233',
      contactEmail: 'sweetsensation.kuto@yopmail.com',
      externalLink: 'https://sweetsensation.com.ng',
      submitterName: 'Sweet Sensation Confectionery Ltd',
      submitterEmail: 'sweetsensation@yopmail.com',
      submitterPhone: '+2348091112233',
      cuisineType: 'Quick Service Bakery & Fast Food',
      priceRange: '$$',
      operatingHours: 'Mon - Sun: 07:00 AM - 10:00 PM',
      menuLink: 'https://sweetsensation.com.ng/menu',
      cacNumber: 'RC-204918',
      licenseNumber: 'OG-FOOD-2021-99',
      isFeatured: false,
      featuredOrder: 0,
    },
    {
      title: 'Olumo View Garden Cafe Ikija',
      description: 'Relaxed garden cafe overlooking the majestic rocks, offering freshly brewed Nigerian coffee, artisan baked treats, smoothies, and light brunch dishes.',
      category: CategoryEnum.lifestyle,
      neighborhood: 'Ikija',
      address: '5 Rock View Lane, Off Ikija Road, Abeokuta',
      latitude: 7.1582,
      longitude: 3.3429,
      thumbnailUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=1080&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=1080&auto=format&fit=crop',
      ],
      legalDocs: [sampleLegalDocs[0]],
      contactPhone: '+2348065554433',
      contactEmail: 'olumoviewcafe@yopmail.com',
      externalLink: 'https://olumoviewcafe.ng',
      submitterName: 'Toluwanimi Adeleke',
      submitterEmail: 'tolu.adeleke@yopmail.com',
      submitterPhone: '+2348065554433',
      cuisineType: 'Artisan Cafe & Brunch',
      priceRange: '$$',
      operatingHours: 'Mon - Sat: 08:30 AM - 07:00 PM',
      menuLink: 'https://olumoviewcafe.ng/menu',
      cacNumber: 'BN-3391829',
      licenseNumber: 'OG-FOOD-2024-12',
      isFeatured: false,
      featuredOrder: 0,
    },
  ];

  for (const rest of restaurants) {
    await prisma.listing.create({
      data: {
        listingType: 'restaurant',
        title: rest.title,
        description: rest.description,
        category: rest.category,
        city: 'Abeokuta',
        neighborhood: rest.neighborhood,
        address: rest.address,
        latitude: rest.latitude,
        longitude: rest.longitude,
        thumbnailUrl: rest.thumbnailUrl,
        legalDocumentUrls: rest.legalDocs,
        contactPhone: rest.contactPhone,
        contactEmail: rest.contactEmail,
        externalLink: rest.externalLink,
        submitterName: rest.submitterName,
        submitterEmail: rest.submitterEmail,
        submitterPhone: rest.submitterPhone,
        status: 'approved',
        isPublished: true,
        isFeatured: rest.isFeatured,
        featuredOrder: rest.featuredOrder,
        images: {
          create: rest.gallery.map((url, idx) => ({
            imageUrl: url,
            sortOrder: idx,
          })),
        },
        restaurantDetails: {
          create: {
            cuisineType: rest.cuisineType,
            priceRange: rest.priceRange,
            operatingHours: rest.operatingHours,
            menuLink: rest.menuLink,
            cacNumber: rest.cacNumber,
            licenseNumber: rest.licenseNumber,
          },
        },
      },
    });
  }
  console.log(`  ✓ Seeded ${restaurants.length} verified Abeokuta restaurants`);

  // 5. Seed Facilities (Abeokuta)
  const facilities = [
    {
      title: 'Federal Medical Centre (FMC) Abeokuta',
      description: 'Premier tertiary healthcare institution in Ogun State offering 24/7 trauma care, specialized surgeries, cardiology, intensive care, and cutting-edge radiology diagnostics.',
      category: CategoryEnum.wellness,
      neighborhood: 'Idi-Aba',
      address: 'Bisi Onabanjo Way, Idi-Aba, Abeokuta, Ogun State',
      latitude: 7.1431,
      longitude: 3.3762,
      thumbnailUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=1080&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=1080&auto=format&fit=crop',
      ],
      legalDocs: [sampleLegalDocs[0], sampleLegalDocs[1], sampleLegalDocs[2]],
      contactPhone: '+2348035551122',
      contactEmail: 'fmcabeokuta@yopmail.com',
      externalLink: 'https://fmcabeokuta.gov.ng',
      submitterName: 'Medical Directorate FMC',
      submitterEmail: 'directorate.fmc@yopmail.com',
      submitterPhone: '+2348035551122',
      facilityCategory: 'Tertiary Hospital & Emergency Trauma Centre',
      emergencyContact: '+2348035551199',
      operatingHours: '24 Hours Emergency & Inpatient Services',
      cacNumber: 'FED-HEALTH-0091',
      licenseNumber: 'MDCN-HOSP-1993-04',
      isFeatured: true,
      featuredOrder: 7,
    },
    {
      title: 'Ogun State Tech Hub & Co-working Space',
      description: 'Modern innovation campus offering high-speed fiber internet, dedicated desks, meeting rooms, hardware maker labs, and startup mentorship programs.',
      category: CategoryEnum.education,
      neighborhood: 'Ibara',
      address: 'Kobape Expressway, Near OOPL, Ibara, Abeokuta',
      latitude: 7.1442,
      longitude: 3.3348,
      thumbnailUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1080&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=1080&auto=format&fit=crop',
      ],
      legalDocs: [sampleLegalDocs[0], sampleLegalDocs[1]],
      contactPhone: '+2348021113344',
      contactEmail: 'oguntechhub@yopmail.com',
      externalLink: 'https://oguntechhub.org',
      submitterName: 'Bureau of Information Technology Ogun',
      submitterEmail: 'ogunbit@yopmail.com',
      submitterPhone: '+2348021113344',
      facilityCategory: 'Technology Hub & Co-working Space',
      emergencyContact: '+2348021113344',
      operatingHours: 'Mon - Sat: 08:00 AM - 09:00 PM',
      cacNumber: 'OGUN-BIT-2019-11',
      licenseNumber: 'OG-INNOV-2020-02',
      isFeatured: true,
      featuredOrder: 8,
    },
    {
      title: 'MKO Abiola International Stadium Complex',
      description: 'Multi-purpose sports arena with Olympic-standard football pitch, tartan track, indoor sports hall, tennis courts, and swimming facilities.',
      category: CategoryEnum.sports,
      neighborhood: 'Kuto',
      address: 'Stadium Road, Kuto, Abeokuta, Ogun State',
      latitude: 7.1391,
      longitude: 3.3510,
      thumbnailUrl: 'https://images.unsplash.com/photo-1577223625816-7546f13df25d?q=80&w=1080&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=1080&auto=format&fit=crop',
      ],
      legalDocs: [sampleLegalDocs[0]],
      contactPhone: '+2348037778899',
      contactEmail: 'mkoabiolastadium@yopmail.com',
      externalLink: 'https://ogunsports.gov.ng/stadium',
      submitterName: 'Ogun State Sports Council',
      submitterEmail: 'sportscouncil.ogun@yopmail.com',
      submitterPhone: '+2348037778899',
      facilityCategory: 'Sports Arena & Athletic Complex',
      emergencyContact: '+2348037778899',
      operatingHours: 'Daily: 06:00 AM - 08:00 PM',
      cacNumber: 'OG-SPORTS-1988',
      licenseNumber: 'NFF-STAD-2021-09',
      isFeatured: false,
      featuredOrder: 0,
    },
    {
      title: 'June 12 Cultural Centre Auditorium',
      description: 'Historic cultural centre and event hall featuring a 2,500-seat amphitheatre, museum gallery, rehearsal rooms, and conference banquet halls.',
      category: CategoryEnum.arts_culture,
      neighborhood: 'Kuto',
      address: 'June 12 Centre Way, Kuto, Abeokuta, Ogun State',
      latitude: 7.1422,
      longitude: 3.3485,
      thumbnailUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?q=80&w=1080&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=1080&auto=format&fit=crop',
      ],
      legalDocs: [sampleLegalDocs[0], sampleLegalDocs[1]],
      contactPhone: '+2348054443322',
      contactEmail: 'june12centre@yopmail.com',
      externalLink: 'https://june12centre.org.ng',
      submitterName: 'Ministry of Culture & Tourism Ogun',
      submitterEmail: 'oguntourism@yopmail.com',
      submitterPhone: '+2348054443322',
      facilityCategory: 'Auditorium & Cultural Centre',
      emergencyContact: '+2348054443322',
      operatingHours: 'Mon - Sat: 08:00 AM - 06:00 PM (Extended for events)',
      cacNumber: 'OG-CULTURE-1994',
      licenseNumber: 'OG-FAC-1995-01',
      isFeatured: false,
      featuredOrder: 0,
    },
    {
      title: 'Simeon Adebo Public Library',
      description: 'Serene public and research library housing over 50,000 academic books, reference journals, E-learning computers, and silent study cubicles.',
      category: CategoryEnum.education,
      neighborhood: 'Kuto',
      address: 'Kuto Roundabout, Kuto, Abeokuta',
      latitude: 7.1418,
      longitude: 3.3465,
      thumbnailUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?q=80&w=1080&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?q=80&w=1080&auto=format&fit=crop',
      ],
      legalDocs: [sampleLegalDocs[0]],
      contactPhone: '+2348022223344',
      contactEmail: 'adebolibrary@yopmail.com',
      externalLink: 'https://adebolibrary.org.ng',
      submitterName: 'Ogun State Library Board',
      submitterEmail: 'ogunlibraryboard@yopmail.com',
      submitterPhone: '+2348022223344',
      facilityCategory: 'Public Library & Research Centre',
      emergencyContact: '+2348022223344',
      operatingHours: 'Mon - Fri: 08:00 AM - 05:00 PM, Sat: 09:00 AM - 02:00 PM',
      cacNumber: 'OG-EDU-1982',
      licenseNumber: 'LIB-NG-1985-02',
      isFeatured: false,
      featuredOrder: 0,
    },
    {
      title: 'Olumo Rock Eco-Tourism Complex',
      description: 'Historical natural sanctuary offering guided rock climbing, elevator summit access, ancient cave exploration, art galleries, and craft souvenir markets.',
      category: CategoryEnum.lifestyle,
      neighborhood: 'Ikija',
      address: 'Ikija, Abeokuta, Ogun State',
      latitude: 7.1594,
      longitude: 3.3444,
      thumbnailUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1080&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?q=80&w=1080&auto=format&fit=crop',
      ],
      legalDocs: [sampleLegalDocs[0], sampleLegalDocs[1]],
      contactPhone: '+2348031234567',
      contactEmail: 'olumorock@yopmail.com',
      externalLink: 'https://olumorock.ng',
      submitterName: 'Ogun Tourism Development Agency',
      submitterEmail: 'oguntourismagency@yopmail.com',
      submitterPhone: '+2348031234567',
      facilityCategory: 'Tourist Attraction & Eco Park',
      emergencyContact: '+2348031234599',
      operatingHours: 'Mon - Sun: 08:30 AM - 06:00 PM',
      cacNumber: 'OG-TOUR-2006',
      licenseNumber: 'NTDC-PARK-2007-01',
      isFeatured: false,
      featuredOrder: 0,
    },
  ];

  for (const fac of facilities) {
    await prisma.listing.create({
      data: {
        listingType: 'facility',
        title: fac.title,
        description: fac.description,
        category: fac.category,
        city: 'Abeokuta',
        neighborhood: fac.neighborhood,
        address: fac.address,
        latitude: fac.latitude,
        longitude: fac.longitude,
        thumbnailUrl: fac.thumbnailUrl,
        legalDocumentUrls: fac.legalDocs,
        contactPhone: fac.contactPhone,
        contactEmail: fac.contactEmail,
        externalLink: fac.externalLink,
        submitterName: fac.submitterName,
        submitterEmail: fac.submitterEmail,
        submitterPhone: fac.submitterPhone,
        status: 'approved',
        isPublished: true,
        isFeatured: fac.isFeatured,
        featuredOrder: fac.featuredOrder,
        images: {
          create: fac.gallery.map((url, idx) => ({
            imageUrl: url,
            sortOrder: idx,
          })),
        },
        facilityDetails: {
          create: {
            facilityCategory: fac.facilityCategory,
            emergencyContact: fac.emergencyContact,
            operatingHours: fac.operatingHours,
            cacNumber: fac.cacNumber,
            licenseNumber: fac.licenseNumber,
          },
        },
      },
    });
  }
  console.log(`  ✓ Seeded ${facilities.length} verified Abeokuta facilities`);

  const total = await prisma.listing.count();
  console.log(`🎉 Seeding finished successfully! Total active Abeokuta listings: ${total}`);
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
